version: "3"
services:

  golang:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080:8080
    networks:
      - mynet
      
  db:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${DB_METHOD}
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  adminer:
    image: adminer
    #restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.docker.localhost`)"
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: 'dracula'
      ADMINER_PLUGINS: "dump-json"
    networks:
      - mynet
networks:
  mynet: