-- \connect "db_dev";

CREATE SEQUENCE carts_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."carts" (
    "id" bigint DEFAULT nextval('carts_id_seq') NOT NULL,
    "id_prodotto" integer NOT NULL,
    "id_user" integer NOT NULL,
    "quantita" integer NOT NULL,
    "prezzo" numeric(8,2) NOT NULL,
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    CONSTRAINT "carts_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE SEQUENCE products_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 14 CACHE 1;

CREATE TABLE "public"."products" (
    "id" bigint DEFAULT nextval('products_id_seq') NOT NULL,
    "nome" character varying(500) NOT NULL,
    "riferimento" character varying(500),
    "categoria" character varying(50) NOT NULL,
    "prezzo_tax_escl" numeric(8,2) NOT NULL,
    "prezzo_tax_incl" numeric(8,2) NOT NULL,
    "quantita" integer NOT NULL,
    "stato" boolean NOT NULL,
    "immagine" character varying(500),
    "riepilogo" text,
    "carta_identita" character varying(50),
    "chi_sono" text,
    "luogo_di_nascita" character varying(500),
    "formazione" text,
    "carattere_e_stile" text,
    "gourmet" character varying(100),
    "musica" character varying(100),
    "cinema" character varying(100),
    "annata" integer,
    "premi" character varying(100),
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "products" ("id", "nome", "riferimento", "categoria", "prezzo_tax_escl", "prezzo_tax_incl", "quantita", "stato", "immagine", "riepilogo", "carta_identita", "chi_sono", "luogo_di_nascita", "formazione", "carattere_e_stile", "gourmet", "musica", "cinema", "annata", "premi", "created_at", "updated_at") VALUES
(1,	'Karma - Primitivo Salento IGT',	'Karma',	'Rossi',	12.30,	15.00,	94,	't',	'http://localhost/storage/Karma.png',	'Sono un mix di tradizioni e culture, il mio stile combina senza fatica maglietta, sneakers e cappello ai miei baffi sempre curati. Posso essere aperto e misterioso allo stesso tempo, il mio profumo è complesso, ricorda sentori di frutti a bacca rossa e ribes, e note di pepe e di spezie.',	'Primitivo Salento IGT',	'Sono dedicato alle sfide quotidiane in cui ogni cosa che fai poi ti torna indietro; l''essenza stessa della vita.',	'Coste Salentine a sud di Brindisi – 80 mt sul livello del mare –raccolta: tra fine settembre ed inizio ottobre. Ho una gradazione alcolica di circa 14,0%.',	'Attingo a diverse fonti e riesco a farle coesistere nel migliore dei modi. La raccolta delle uve avviene in più fasi. La prima raccolta viene effettuata a piena maturità aromatica per conferire integrità e tipicità. La seconda raccolta avviene in surmaturazione. La vinificazione avviene separata per singola raccolta e maturazione.  Dopo l’assemblaggio, riposo per un mese in vasca prima dell’imbottigliamento.',	'Sono un mix di tradizioni e culture, posso essere aperto e misterioso allo stesso tempo, il mio profumo è complesso, ricorda sentori di frutti a bacca rossa e ribes, e note di pepe e di spezie.',	'Assieme di formaggi',	'Karma Police – Radiohead',	'Sliding Doors',	NULL,	NULL,	NULL,	NULL),
(2,	'Link Magnum - Brut Rosè',	'Link Magnum',	'Magnum',	26.23,	32.00,	100,	't',	'http://localhost/storage/Karma.png',	'Mi presento con delicatezza ma sono audace e complesso. Mi piace essere raffinato, fresco con un perlate fine e persistente. Ho un ventaglio di profumi nitidi e aromatici che mi rendono seducente e ricercato.',	'Brut rosè spumante Modena DOC Millesimato',	'Sono LINK la Mascotte di Ferro13, Hacker, Nerd, Hashtag, Hipster e Gentleman sono i miei amici. Sono fresco, vivace e seducente.',	'Colline Modenesi, a sud di Modena, circa 170 metri di altitudine. Il mio vitigno è il Grasparossa e ho una gradazione alcolica di 12,0% gradi.',	'Unisco la gioia di stare assieme alla gente all’attenzione del particolare. Le uve vengono raccolte ed immediatamente portate in vinificazione. Gli acini vengono aperti: succo e bucce rimangono nella pressa per qualche ora ad una temperatura molto fresca. La spumantizzazione segue un processo lento di almeno 40 giorni che dona un perlate elegante,fine e profumato.',	'Mi presento con delicatezza ma sono audace e complesso. Mi piace essere raffinato, fresco con un perlate fine e persistente. Ho un ventaglio di profumi nitidi e aromatici che mi rendono seducente e ricercato.',	'Come una buona Mascotte sono il compagno ideale per ogni occasione',	'Ordinary pleasure. – Toro y Moi',	'Il Gigante di Ferro',	NULL,	NULL,	NULL,	NULL),
(3,	'The Boss Rosé - Pimp my bottle edition',	'The Boss Rosè',	'Spumanti',	15.57,	19.00,	0,	'f',	'',	'Il vero Boss della famiglia è la mamma e l’ iconica bottiglia di Procecco DOC The Boss Rosé viene proposta in una versione inedita tutta da “pimpare”. Fino a domenica 8 maggio assieme alla bottiglia si riceveranno dei colorati sticker a tema per personalizzare la propria bottiglia e utilizzarla come vaso unconventional con i fiori di Frida''s (www.fridas.it) offerti per l''occasione in sconto del 20%.',	'Pimp my bottle edition',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	'SognoDivino Hashtag - Sauvignon Limited Edition',	'SognoDivino Hashtag',	'Bianchi',	16.39,	20.00,	8,	'f',	'',	'Una speciale box realizzata in collaborazione con l’illustratrice Momusso.',	'Sauvignon Limited Edition',	'Ferro13 presenta “Sognodivino” per celebrare l’amore in tutte le sue espressioni e sfumature. “Sognodivino” è la speciale box illustrata da Martina Lorusso, in arte Momusso, che ha anche ideato la parola "Sognodivino". Un’espressione che vuole comunicare l’unione d’intenti e l’amore che si provano sorseggiando un buon calice di vino in compagnia di persone care. La scatola al suo interno racchiude l''universo delle possibilità che un incontro o un dialogo possono aprire.',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	'OLD - Vermouth di Torino',	'OLD',	'Products',	31.97,	39.00,	391,	't',	'',	'Sono un Vermouth di Torino in cui, il vino, frutto dell’unione di #Hashtag e Gentleman, è protagonista con le sue note varietali, in perfetto stile Ferro13. Piccoli frutti rossi, profumo di agrumi e una sottile speziatura fanno di me un elegante Vermouth da bere sia liscio, che in grado di arricchire i grandi cocktails. Limited edition di 1713 bottiglie',	'Vermouth di Torino',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(6,	'The Boss Rosé - Prosecco DOC Millesimato Brut',	'The Boss Rosé',	'Spumanti',	13.52,	16.50,	44,	't',	'',	'Sono un tipo deciso, con un carattere forte ed equilibrato allo stesso tempo. Ho un colore rosa brillante. Il mio profumo è intenso, con sentori delicati di fiori bianchi, mela, pera, tipici del Prosecco che si fondono con note di frutti rossi. Il mio sapore è fresco, vellutato con una buona acidità. Sono sapido, con un finale asciutto e persistente. Vellutato, fresco, ben equilibrato, vivace con un retrogusto elegante. Ho un perlage fine e persistente. Sono socievole, la mia personalità e il mio stile affascinano e attraggono le persone. Mi piace essere trasversale, mi all’antipasto di crudités di pesce, come pure ai primi e secondi piatti delicati.',	'Prosecco DOC Millesimato Brut',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	2019,	NULL,	NULL,	NULL),
(7,	'Hacker Magnum - Sangiovese Toscana IGT',	'Hacker Magnum',	'Magnum',	27.87,	16.50,	23,	't',	'',	'Cosmopolita e sportivo, mi apprezzano per la struttura combinata alla freschezza e per il profumo che ricorda note di viola mammola e di piccoli frutti rossi.',	'Sangiovese Toscana IGT',	'Sono l’alterego di 01101101 01110010 01111000, comunicazione e digitale sono il mio mondo, computer e devices i miei strumenti.',	'Cuore della Toscana – colline di Greve in Chianti a 300 mt sul livello del mare – raccolta: fine settembre. Gradazione alcolica compresa tra gli 13,0% ed i 13,5% in relazione all’annata.',	'Rispettosa della tradizione ma con occhi verso l’innovazione, la mia vinificazione avviene separata per singolo appezzamento e terroir cosi come la maturazione. Terminato il periodo di maturazione,  il blend viene assemblato e riposo per un mese in vasca prima di essere imbottigliato.',	'Cosmopolita e sportivo, mi apprezzano per la struttura combinata alla freschezza e per il profumo che ricorda note di viola mammola e di piccoli frutti rossi.',	'Fiorentina con verdure grigliate',	'Jazz – ECM records',	'In Time',	NULL,	NULL,	NULL,	NULL),
(8,	'The Boss Magnum - Prosecco DOC Millesimato Extra Dry',	'The Boss Magnum',	'Magnum',	30.33,	37.00,	71,	't',	'',	'Sono un tipo deciso, con un carattere forte ed equilibrato allo stesso tempo. Ho un perlage fresco mentre il mio profumo ricorda note fruttate e floreali. Sono socievole, la mia personalità e il mio stile affascinano e attraggono le persone.',	'Prosecco DOC Millesimato Extra Dry',	'Sono il leader, sono la guida, sono la visione di 4 amici appassionati di digitale e innovazione che vedono il vino come un mezzo di comunicazione di cultura contemporanea.',	'Colline della Marca Trevigiana, a nord di Treviso, circa 100 metri di altitudine. Ho una gradazione alcolica di 11,5% gradi.',	'Le uve vengono raccolte in epoche diverse tra settembre e ottobre per ottenere un ampio ventaglio di profumi e sensazioni. La spumantizzazione viene effettuata utilizzando lieviti indigeni “Madre” delle masse già pronte per il consumo. La spumantizzazione è lenta, circa 50-70 giorni. Questo mi permette di raggiungere finezza del perlage e maggiore freschezza.',	'Sono un tipo deciso, con un carattere forte ed equilibrato allo stesso tempo. Ho un perlage fresco mentre il mio profumo ricorda note fruttate e floreali. Sono socievole, la mia personalità e il mio stile affascinano e attraggono le persone.',	'Sono il re dell’aperitivo ma apprezzo tutta la buona cucina',	'Born in the U.S.A. – Bruce Springsteen',	'The Big Lebowski',	NULL,	NULL,	NULL,	NULL),
(9,	'Hacker - Sangiovese Toscana IGT',	'Hacker',	'Rossi',	12.30,	15.00,	269,	't',	'',	'Cosmopolita e sportivo, mi apprezzano per la struttura combinata alla freschezza e per il profumo che ricorda note di viola mammola e di piccoli frutti rossi.',	'Sangiovese Toscana IGT',	'Sono l’alterego di 01101101 01110010 01111000, comunicazione e digitale sono il mio mondo, computer e devices i miei strumenti.',	'Cuore della Toscana – colline di Greve in Chianti a 300 mt sul livello del mare – raccolta: fine settembre. Gradazione alcolica compresa tra gli 13,0% ed i 13,5% in relazione all’annata.',	'Rispettosa della tradizione ma con occhi verso l’innovazione, la mia vinificazione avviene separata per singolo appezzamento e terroir cosi come la maturazione. Terminato il periodo di maturazione,  il blend viene assemblato e riposo per un mese in vasca prima di essere imbottigliato.',	'Cosmopolita e sportivo, mi apprezzano per la struttura combinata alla freschezza e per il profumo che ricorda note di viola mammola e di piccoli frutti rossi.',	'Fiorentina con verdure grigliate',	'Jazz – ECM records',	'In Time',	NULL,	NULL,	NULL,	NULL),
(10, 'Gentleman - Pinot Nero Oltrepò Pavese DOC',	'Gentleman',	'Rossi',	13.11,	16.00,	97,	't',	'',	'Prediligo uno stile classico ed elegante, abito e cravatta sempre, anche in vigna. Non sono esuberante, preferisco farmi scoprire a poco a poco, mi apprezzano per la mia personalità unica e per il profumo che ricorda note di frutti rossi e ribes.',	'Pinot Nero Oltrepò Pavese DOC',	'Sono l’alterego di MARCO BERNABEI, la prova vivente che i Gentleman esistono ancora, educati, rispettosi, coerenti con i loro valori, nella vita e nel lavoro.',	'Colline Pavesi – 130 mt sul livello del mare – raccolta: seconda decade di settembre. Ho una gradazione alcolica compresa tra i 12,5% ed i 13,0% in relazione all’annata.',	'Un Gentleman non può che avere una formazione classica con forti punti di riferimento. Quindi, vinificazione in stile Borgogna, in tini troncoconici di legno di 30 quintali l’uno a temperatura non controllata. È una vinificazione lenta e precisa e le tecniche del delestage e del batonage mi consentono di effettuare contemporaneamente anche la fermentazione malolattica. Dopo la svinatura, resto ad affinare sui lieviti per circa 9 mesi.',	'Prediligo uno stile classico ed elegante, abito e cravatta sempre, anche in vigna. Non sono esuberante, preferisco farmi scoprire a poco a poco, mi apprezzano per la mia personalità unica e per il profumo che ricorda note di frutti rossi e ribes.',	'Tagliolini al tartufo',	'A Sky Full of Stars – Coldplay',	'Casablanca',	NULL,	NULL,	NULL,	NULL),
(11, 'Hipster - Negroamaro Puglia IGT',	'Hipster',	'Rossi',	9.84,	12.00,	614,	't',	'',	'Sono un mix di tradizioni e culture, il mio stile combina senza fatica maglietta, sneakers e cappello ai miei baffi sempre curati. Posso essere aperto e misterioso allo stesso tempo, il mio profumo è complesso, ricorda sentori di frutti a bacca rossa e ribes, e note di pepe e di spezie.',	'Negroamaro Puglia IGT',	'Sono l’alterego di GABRIELE STRINGA, il creativo del gruppo, sono una sintesi di passato e futuro, espressione di una cultura internazionale che ha fatto di barba e baffi, il suo segno distintivo.',	'Coste Salentine a sud di Brindisi – 80 mt sul livello del mare –raccolta: tra fine settembre ed inizio ottobre. Ho una gradazione alcolica di circa 13,0%.',	'Attingo a diverse fonti e riesco a farle coesistere nel migliore dei modi. La raccolta delle uve avviene in più fasi. La prima raccolta viene effettuata a piena maturità aromatica per conferire integrità e tipicità. La seconda raccolta avviene in surmaturazione. La vinificazione avviene separata per singola raccolta e maturazione.  Dopo l’assemblaggio, riposo per un mese in vasca prima dell’imbottigliamento.',	'Sono un mix di tradizioni e culture, il mio stile combina senza fatica maglietta, sneakers e cappello ai miei baffi sempre curati. Posso essere aperto e misterioso allo stesso tempo, il mio profumo è complesso, ricorda sentori di frutti a bacca rossa e ribes, e note di pepe e di spezie.',	'Tapas alla Basca',	'Wake up – Arcade Fire',	'The Royal Tenenbaums',	NULL,	NULL,	NULL,	NULL),
(12, 'Hashtag - Sauvignon',	'Hashtag',	'Bianchi',	13.11,	16.00,	1130,	't',	'',	'Sono un tipo moderno, socievole, attento alle tendenze e ai cambiamenti. Vivo calato nella realtà e sono espressione dei sentimenti delle persone. Mi apprezzano per la mia spiccata acidità e mineralità, il mio profumo ricorda fiori bianchi e note di peperone.',	'Sauvignon varietale Italia',	'Sono l’alterego di ALBERTO ZAMPINI, sono un simbolo di aggregazione, unisco contenuti e parole chiave, vivo nei social media, rappresento il presente e il futuro.',	'Colline del Veneto orientale. Raccolta: primi giorni di settembre. Ho una gradazione alcolica di 12,5%',	'Le mie uve vengono raccolte a bassa temperatura e mantenute in macerazione a freddo per circa 7 giorni. Dopo la spremitura, quando sono ancora mosto, fermento a temperature non superiori a 14°C per tutta la durata della vinificazione che dura circa 30-40 giorni. Resto sui lieviti per oltre 3 mesi con continui batonage che mi permettono di mantenere inalterati i profumi. Dopo l’assemblaggio riposo per un mese in vasca prima dell’imbottigliamento.',	'Sono un tipo moderno, socievole, attento alle tendenze e ai cambiamenti. Vivo calato nella realtà e sono espressione dei sentimenti delle persone. Mi apprezzano per la mia spiccata acidità e mineralità, il mio profumo ricorda fiori bianchi e note di peperone.',	'Sushi e sashimi, pesce crudo cucina fusion',	'I can’t get no satisfaction – Rolling Stones',	'Sideways – In viaggio con Jack',	NULL,	NULL,	NULL,	NULL),
(13, 'Ferro13 Weekender (conf.6)',	'Ferro13 Weekender (conf.6)',	'Confezioni',	81.15,	99.00,	98,	't',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(14, 'Nerd - Nero d''Avola DOC',	'Nerd',	'Rossi',	9.83,	12.00,	91,	't',	'',	'All’apparenza morbido, rivelo un carattere forte e deciso, mi apprezzano proprio per questa identità e personalità precisa. Il mio profumo ricorda note floreali e speziate di anice e cannella.',	'Nero d\''Avola Sicilia DOC',	'Sono l’alterego di ALBERTO BURATTO, l’uomo delle analisi e dei numeri, veneto di nascita, siciliano di adozione per 15 anni.',	'Coste Siracusane a 50 mt sul livello del mare – raccolta: a settembre. Ho una gradazione alcolica compresa tra gli 13,0% ed i 13,5% in relazione all’annata.',	'La mia capacità di analisi è frutto di esperienza e carattere. Le uve vengono pre-macerate per trasferire con delicatezza i profumi ed i colori e vinificate separatamente per conservare le caratteristiche di ogni appezzamento. Il carattere finale è enfatizzato dalla permanenza per 6 mesi in acciaio sui lieviti.',	'All’apparenza morbido, rivelo un carattere forte e deciso, mi apprezzano proprio per questa identità e personalità precisa. Il mio profumo ricorda note floreali e speziate di anice e cannella.',	'Barbeque e tutto ciò che si può grigliare',	'Echoes – Pink floyd',	'Matrix',	NULL,	NULL,	NULL,	NULL);

CREATE SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."users" (
    "id" bigint DEFAULT nextval('users_id_seq') NOT NULL,
    "nome" character varying(255) NOT NULL,
    "cognome" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "password" character varying(255) NOT NULL,
    "telefono" integer,
    "indirizzo_fattura" character varying(255),
    "indirizzo_spedizione" character varying(255),
    "api_token" character varying(80),
    "remember_token" character varying(100),
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    CONSTRAINT "users_api_token_unique" UNIQUE ("api_token"),
    CONSTRAINT "users_email_unique" UNIQUE ("email"),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

ALTER TABLE ONLY "public"."carts" ADD CONSTRAINT "carts_id_prodotto_foreign" FOREIGN KEY (id_prodotto) REFERENCES products(id) ON DELETE CASCADE NOT DEFERRABLE;

